[package]
name = "java_vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.zip]
version = "0.5.4"
default-features = false
features = ["deflate"]

[dependencies]
binrw = "0.8.0"